"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import ProviderRedux from '@/redux/ProviderRedux'
import ProjectsPage from './projects/ProjectsPage';
import { usePathname, useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isProjectRoute = pathname.startsWith('/projects');

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ProviderRedux>
          {isProjectRoute && <ProjectsPage />}
          {children}
        </ProviderRedux>
      </body>
    </html>
  )
}