"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import ProviderRedux from '@/redux/ProviderRedux'
import ProjectsPage from './projects/ProjectsPage';
import { usePathname } from 'next/navigation';
import { initReactI18next, useTranslation } from 'react-i18next';
import global_en from '@/config/languages/en/global.json'
import global_es from '@/config/languages/es/global.json'
import i18next from 'i18next';
import { useEffect } from 'react';
import { ThemeProvider } from 'next-themes';
import LanguageProvider from '@/components/prueba/LanguageProvider';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

i18next
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        global: global_en,
      },
      es: {
        global: global_es,
      },
    },
    lng: "en",
    fallbackLng: "en",
    interpolation: {
      escapeValue: false
    }
  });

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const isProjectRoute = pathname.startsWith('/projects');
  const [t, i18n] = useTranslation("global");

  useEffect(() => {
    const language = localStorage.getItem("language");
    i18n.changeLanguage(language);
  }, []);

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          enableSystem={true}
          defaultTheme="system"
        >
          <ProviderRedux>
              {isProjectRoute && <ProjectsPage />}
              {children}
          </ProviderRedux>
        </ThemeProvider>
      </body>
    </html>
  )
}